name: Events exercices

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'dev'
        required: true
        default: 'dev' 


jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)